/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Allocate `size` bytes on the heap and return the pointer as a decimal string.
 * Memory is NOT zero-initialised (mirrors malloc). Use `unsafe_calloc` for zeroed.
 */
export declare function unsafeMalloc(size: number): string
/** Allocate `size` bytes, zero-initialised (mirrors calloc). */
export declare function unsafeCalloc(size: number): string
/**
 * Reallocate a previous allocation to a new size. Returns the new pointer.
 * The old pointer is invalidated even if reallocation fails.
 */
export declare function unsafeRealloc(pointer: string, newSize: number): string
/** Free a previously allocated pointer. */
export declare function unsafeFree(pointer: string): void
/** Attach a human-readable tag to an allocation (for heap dumps / debugging). */
export declare function unsafeTag(pointer: string, tag: string): void
/** Read `length` raw bytes from pointer. Returns a Buffer. */
export declare function unsafeRead(pointer: string, length: number): Array<number>
/** Read a UTF-8 string from pointer up to `length` bytes. */
export declare function unsafeReadString(pointer: string, length: number): string
/** Read a u8 at pointer. */
export declare function unsafeReadU8(pointer: string): number
/** Read a u16 at pointer (little-endian). */
export declare function unsafeReadU16(pointer: string): number
/** Read a u32 at pointer (little-endian). */
export declare function unsafeReadU32(pointer: string): number
/** Read an i32 at pointer (little-endian). */
export declare function unsafeReadI32(pointer: string): number
/** Read an i64 at pointer (little-endian). Returns as string to avoid JS precision loss. */
export declare function unsafeReadI64(pointer: string): string
/** Read an f32 at pointer (little-endian). */
export declare function unsafeReadF32(pointer: string): number
/** Read an f64 at pointer (little-endian). */
export declare function unsafeReadF64(pointer: string): number
/** Write raw bytes to pointer. */
export declare function unsafeWrite(pointer: string, bytes: Array<number>): void
/** Write a UTF-8 string to pointer. */
export declare function unsafeWriteString(pointer: string, value: string): void
/** Write a u8 to pointer. */
export declare function unsafeWriteU8(pointer: string, value: number): void
/** Write a u16 to pointer (little-endian). */
export declare function unsafeWriteU16(pointer: string, value: number): void
/** Write a u32 to pointer (little-endian). */
export declare function unsafeWriteU32(pointer: string, value: number): void
/** Write an i32 to pointer (little-endian). */
export declare function unsafeWriteI32(pointer: string, value: number): void
/** Write an i64 to pointer (little-endian). Accepts string to avoid JS precision loss. */
export declare function unsafeWriteI64(pointer: string, value: string): void
/** Write an f32 to pointer (little-endian). */
export declare function unsafeWriteF32(pointer: string, value: number): void
/** Write an f64 to pointer (little-endian). */
export declare function unsafeWriteF64(pointer: string, value: number): void
/** Copy `size` bytes from `src` to `dst`. Regions must not overlap — use unsafe_memmove for overlapping regions. */
export declare function unsafeMemcopy(src: string, dst: string, size: number): void
/** Copy `size` bytes from `src` to `dst`. Safe for overlapping regions. */
export declare function unsafeMemmove(src: string, dst: string, size: number): void
/** Fill `size` bytes at `pointer` with `value`. */
export declare function unsafeMemset(pointer: string, value: number, size: number): void
/** Compare `size` bytes at `a` and `b`. Returns true if equal. */
export declare function unsafeMemcmp(a: string, b: string, size: number): boolean
/**
 * Add a signed byte offset to a pointer. Returns new pointer string.
 * Does NOT register the result — it is a view into an existing allocation.
 */
export declare function unsafePtrOffset(pointer: string, offset: number): string
/** Subtract two pointers and return the byte difference as a signed string. */
export declare function unsafePtrDiff(a: string, b: string): string
/** Return the size of the allocation at this pointer. */
export declare function unsafeAllocSize(pointer: string): number
/** Return true if the pointer is a known live allocation. */
export declare function unsafeIsValid(pointer: string): boolean
/**
 * Return the size in bytes of a primitive type name.
 * Accepts: u8, u16, u32, u64, i8, i16, i32, i64, f32, f64, ptr
 */
export declare function unsafeSizeof(typeName: string): number
/** Return a formatted hex dump of `length` bytes at `pointer`. */
export declare function unsafeHexDump(pointer: string, length: number): string
/** Return a JSON summary of all live allocations. */
export declare function unsafeListAllocations(): string
/** Return count of live allocations and total bytes allocated. */
export declare function unsafeStats(): string
